/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author Oswald David
 */
public class VentanaAccion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAccion
     */
    public VentanaAccion() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buttonBailar = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_028.jpg"))); // NOI18N
        jLabel1.setEnabled(false);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_030.jpg"))); // NOI18N
        jLabel2.setEnabled(false);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_032.jpg"))); // NOI18N
        jLabel3.setEnabled(false);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_034.jpg"))); // NOI18N
        jLabel4.setEnabled(false);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_036.jpg"))); // NOI18N
        jLabel5.setEnabled(false);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_038.jpg"))); // NOI18N
        jLabel6.setEnabled(false);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_040.jpg"))); // NOI18N
        jLabel7.setEnabled(false);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_042.jpg"))); // NOI18N
        jLabel8.setEnabled(false);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_044.jpg"))); // NOI18N
        jLabel9.setEnabled(false);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_046.jpg"))); // NOI18N
        jLabel10.setEnabled(false);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_048.jpg"))); // NOI18N
        jLabel11.setEnabled(false);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_050.jpg"))); // NOI18N
        jLabel12.setEnabled(false);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_052.jpg"))); // NOI18N
        jLabel13.setEnabled(false);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clases/BaileAccion_054.jpg"))); // NOI18N
        jLabel14.setEnabled(false);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 730));

        buttonBailar.setBackground(new java.awt.Color(255, 204, 0));
        buttonBailar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        buttonBailar.setForeground(new java.awt.Color(255, 102, 0));
        buttonBailar.setText("DANCE");
        buttonBailar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonBailar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBailarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBailar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 100, 365));

        buttonNext.setBackground(new java.awt.Color(51, 51, 51));
        buttonNext.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        buttonNext.setForeground(new java.awt.Color(255, 255, 255));
        buttonNext.setText("NEXT");
        buttonNext.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });
        jPanel1.add(buttonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 363, 100, 183));

        buttonBack.setBackground(new java.awt.Color(51, 51, 51));
        buttonBack.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(255, 255, 255));
        buttonBack.setText("BACK");
        buttonBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 542, 100, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private int contador = 0;
    private void buttonBailarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBailarActionPerformed
         contador++;
        if (contador == 1) {
            jLabel1.setEnabled(true);
        }
        if (contador == 2) {
            jLabel1.setEnabled(false);
            jLabel1.setVisible(false);
            jLabel2.setEnabled(true);
        }
        if (contador == 3) {
            jLabel2.setEnabled(false);
            jLabel2.setVisible(false);
            jLabel3.setEnabled(true);
        }
        if (contador == 4) {
            jLabel3.setEnabled(false);
            jLabel3.setVisible(false);
            jLabel4.setEnabled(true);
        }
        if (contador == 5) {
            jLabel4.setEnabled(false);
            jLabel4.setVisible(false);
            jLabel5.setEnabled(true);
        }
        if (contador == 6) {
            jLabel5.setEnabled(false);
            jLabel5.setVisible(false);
            jLabel6.setEnabled(true);
        }
        if (contador == 7) {
            jLabel6.setEnabled(false);
            jLabel6.setVisible(false);
            jLabel7.setEnabled(true);
        }
        if (contador == 8) {
            jLabel7.setEnabled(false);
            jLabel7.setVisible(false);
            jLabel8.setEnabled(true);
        }
        if (contador == 9) {
            jLabel8.setEnabled(false);
            jLabel8.setVisible(false);
            jLabel9.setEnabled(true);
        }
        if (contador == 10) {
            jLabel9.setEnabled(false);
            jLabel9.setVisible(false);
            jLabel10.setEnabled(true);
        }
        if (contador == 11) {
            jLabel10.setEnabled(false);
            jLabel10.setVisible(false);
            jLabel11.setEnabled(true);
        }
        if (contador == 12) {
            jLabel11.setEnabled(false);
            jLabel11.setVisible(false);
            jLabel12.setEnabled(true);
        }
        if (contador == 13) {
            jLabel12.setEnabled(false);
            jLabel12.setVisible(false);
            jLabel13.setEnabled(true);
        }
        if (contador == 14) {
            jLabel13.setEnabled(false);
            jLabel13.setVisible(false);
            jLabel14.setEnabled(true);
        }
    }//GEN-LAST:event_buttonBailarActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        Ventana5Concesionario ventana5 = new Ventana5Concesionario();
        ventana5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        Ventana3 ventana3 = new Ventana3();
        ventana3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonBailar;
    private javax.swing.JButton buttonNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
